# Remote
remote:
  - platform: xiaomi_miio
    name: Mi Universal Remote
    host: YOUR_REMOTE_IP
    token: YOUR_TOKEN
    slot: 1
    timeout: 30
    commands:
        # Samsung Smart TV UE40F6510 
        turn_on_tv:
            command:
                - raw:Z6UPAS8CAACbBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAQAAAAAAAAEAAQEBAQEBAwIhAQEAAAAAAAEBAQAAAAAAAAEAAAAAAAABAAEBAQEBAQMCIQEBAAAAAAABAQEAAAAAAAABAAAAAAAAAQABAQEBAQEDAiEBAQAAAAAAAQEBAAAAAAAAAQAAAAAAAAEAAQEBAQEBAA
        btn_signal_source:
            command:
                - raw:Z6WHADACAACaBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAAAAAAAAAABAQEBAQEBAwIhAQEAAAAAAAEBAQAAAAAAAQAAAAAAAAAAAQEBAQEBAQAA==
        number_1:
            command:
                - raw:Z6WHADECAACVBgAAhxEAAKgRAADIEQAANLcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkEBAQAAAAAAAQEBAAAAAAAAAAEAAAAAAAEBAAEBAQEBBQMxAQEAAAAAAAEBAQAAAAAAAAABAAAAAAABAQABAQEBAQAA==
        number_2:
            command:
                - raw:Z6WHADACAACaBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAEAAAAAAAABAAEBAQEBAwIhAQEAAAAAAAEBAQAAAAAAAQABAAAAAAAAAQABAQEBAQAA==
        number_3:
            command:
                - raw:Z6WHAC8CAACbBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAQEAAAAAAAEAAAEBAQEBAwIhAQEAAAAAAAEBAQAAAAAAAAEBAAAAAAABAAABAQEBAQAA==
        number_4:
            command:
                - raw:Z6WHABACAABRAgAAdgYAAHQRAADcEQAANLcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0ISEhAQEBAQEhISEBAQEBAQEBASEBAQEBISEhASEhISFRNCEhIQEBAQEBISEhAQEBAQEBAQEhAQEBASEhIQEhISEhAQ==
        number_5:
            command:
                - raw:Z6WHAC8CAACcBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAABAAAAAAABAQABAQEBAwIhAQEAAAAAAAEBAQAAAAAAAQAAAQAAAAAAAQEAAQEBAQAA==
        number_6:
            command:
                - raw:Z6WHACMCAABBAgAAhAYAAI4RAADDEQAA5hEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1ISEhAQEBAQEhISEBAQEBAQEhASEBAQEBIQEhASEhISFhNCEhIQEBAQEBISEhAQEBAQEBIQEhAQEBASEBIQEhISEhAQ==
        number_7:
            command:
                - raw:Z6WHADUCAACHBgAAjhEAAMERAAA0twAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjEBAQAAAAAAAQEBAAAAAAAAAAEBAAAAAAEBAAABAQEBBAIxAQEAAAAAAAEBAQAAAAAAAAABAQAAAAABAQAAAQEBAQAA==
        number_8:
            command:
                - raw:Z6WHAC4CAACfBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAEBAAAAAAABAAABAQEBAwIhAQEAAAAAAAEBAQAAAAAAAQABAQAAAAAAAQAAAQEBAQAA==
        number_9:
            command:
                - raw:Z6WHAC4CAACfBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAQEBAAAAAAEAAAABAQEBAwIhAQEAAAAAAAEBAQAAAAAAAAEBAQAAAAABAAAAAQEBAQAA==
        number_0:
            command:
                - raw:Z6WHAC8CAACbBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAAAAQAAAAABAQEAAQEBAwIhAQEAAAAAAAEBAQAAAAAAAQAAAAEAAAAAAQEBAAEBAQAA==
        ttx_mix:
            command:
                - raw:Z6WHAC4CAACfBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAAEBAAEAAAEBAAABAAEBAwIhAQEAAAAAAAEBAQAAAAAAAAABAQABAAABAQAAAQABAQAA==
        pre_ch:
            command:
                - raw:Z6WHAC4CAACfBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAQAAAQAAAAAAAQEAAQEBAwIhAQEAAAAAAAEBAQAAAAAAAQEAAAEAAAAAAAEBAAEBAQAA==
        volume_up:
            command:
                - raw:Z6XLAC4CAACfBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAQEAAAAAAAAAAAEBAQEBAwIhAQEAAAAAAAEBAQAAAAAAAQEBAAAAAAAAAAABAQEBAQMCIQEBAAAAAAABAQEAAAAAAAEBAQAAAAAAAAAAAQEBAQEAA=
        volume_down:
            command:
                - raw:Z6WHADYCAACEBgAAjBEAAMERAAA0twAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjEBAQAAAAAAAQEBAAAAAAABAQABAAAAAAAAAQABAQEBBAIxAQEAAAAAAAEBAQAAAAAAAQEAAQAAAAAAAAEAAQEBAQAA==
        btn_mute:
            command:
                - raw:Z6WHAC4CAACfBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAQEBAAAAAAAAAAABAQEBAwIhAQEAAAAAAAEBAQAAAAAAAQEBAQAAAAAAAAAAAQEBAQAA==
        btn_ch_list:
            command:
                - raw:Z6WHAC8CAACbBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAQABAAEBAAAAAQABAAABAwIhAQEAAAAAAAEBAQAAAAAAAQEAAQABAQAAAAEAAQAAAQAA==
        program_up:
            command:
                - raw:Z6WHAC8CAACcBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAQAAAQAAAAEAAQEAAQEBAwIhAQEAAAAAAAEBAQAAAAAAAAEAAAEAAAABAAEBAAEBAQAA==
        program_down:
            command:
                - raw:Z6WHAC8CAACdBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAAAAAQAAAAEBAQEAAQEBAwIhAQEAAAAAAAEBAQAAAAAAAAAAAAEAAAABAQEBAAEBAQAA==
        btn_menu:
            command:
                - raw:Z6WHAC4CAACeBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAQABAQAAAAEAAQAAAQEBAwIhAQEAAAAAAAEBAQAAAAAAAAEAAQEAAAABAAEAAAEBAQAA==
        btn_smart_hub:
            command:
                - raw:Z6WHADACAACaBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAABAQEBAAABAQAAAAABAwIhAQEAAAAAAAEBAQAAAAAAAQAAAQEBAQAAAQEAAAAAAQAA==
        btn_guide:
            command:
                - raw:Z6WHADECAACTBgAAhhEAAKgRAADKEQAANLcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkEBAQAAAAAAAQEBAAAAAAABAQEBAAABAAAAAAABAQABBQMxAQEAAAAAAAEBAQAAAAAAAQEBAQAAAQAAAAAAAQEAAQAA==
        btn_tools:
            command:
                - raw:Z6WHAC8CAACdBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAQABAAABAAAAAQABAQABAwIhAQEAAAAAAAEBAQAAAAAAAQEAAQAAAQAAAAEAAQEAAQAA==
        btn_info:
            command:
                - raw:Z6WHAC8CAACaBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAQEBAQAAAAAAAAAAAQEBAwIhAQEAAAAAAAEBAQAAAAAAAQEBAQEAAAAAAAAAAAEBAQAA==
        btn_ok:
            command:
                - raw:Z6WHAC4CAACeBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAAABAAEBAAEBAQABAAABAwIhAQEAAAAAAAEBAQAAAAAAAAAAAQABAQABAQEAAQAAAQAA==
        arrow_up:
            command:
                - raw:Z6WHADACAACZBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAAAAAAEBAAEBAQEBAAABAwIhAQEAAAAAAAEBAQAAAAAAAAAAAAABAQABAQEBAQAAAQAA==
        arrow_left:
            command:
                - raw:Z6WHAC8CAACdBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAEAAAEBAAABAAEBAAABAwIhAQEAAAAAAAEBAQAAAAAAAQABAAABAQAAAQABAQAAAQAA==
        arrow_right:
            command:
                - raw:Z6VDAC4CAACfBgAApxEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAQAAAAEBAAEAAQEBAAABAA
        arrow_down:
            command:
                - raw:Z6WHAC8CAACcBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAAAAAEBAAABAQEBAAABAwIhAQEAAAAAAAEBAQAAAAAAAQAAAAABAQAAAQEBAQAAAQAA==
        btn_return:
            command:
                - raw:Z6WHAC4CAACfBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAAABAQABAAEBAQAAAQABAwIhAQEAAAAAAAEBAQAAAAAAAAAAAQEAAQABAQEAAAEAAQAA==
        btn_exit:
            command:
                - raw:Z6WHAC4CAACfBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAEBAAEAAAABAAABAAEBAwIhAQEAAAAAAAEBAQAAAAAAAQABAQABAAAAAQAAAQABAQAA==
        btn_a_red:
            command:
                - raw:Z6WHAC4CAACgBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAAEBAAEBAAEBAAABAAABAwIhAQEAAAAAAAEBAQAAAAAAAAABAQABAQABAQAAAQAAAQAA==
        btn_b_green:
            command:
                - raw:Z6WHAC4CAACfBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAAEAAQAAAAEBAAEAAQEBAwIhAQEAAAAAAAEBAQAAAAAAAAABAAEAAAABAQABAAEBAQAA==
        btn_c_yellow:
            command:
                - raw:Z6WHAC4CAACfBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAEAAQAAAAABAAEAAQEBAwIhAQEAAAAAAAEBAQAAAAAAAQABAAEAAAAAAQABAAEBAQAA==
        btn_d_blue:
            command:
                - raw:Z6WHAC8CAACcBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAQEAAQAAAAEAAAEAAQEBAwIhAQEAAAAAAAEBAQAAAAAAAAEBAAEAAAABAAABAAEBAQAA==
        btn_e_manual:
            command:
                - raw:Z6WHAC4CAACfBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAQEBAQEAAAAAAAAAAAEBAwIhAQEAAAAAAAEBAQAAAAAAAQEBAQEBAAAAAAAAAAABAQAA==
        btn_3_d:
            command:
                - raw:Z6WHAC8CAACbBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAQEBAQAAAQAAAAAAAQEAAwIhAQEAAAAAAAEBAQAAAAAAAQEBAQEAAAEAAAAAAAEBAAAA==
        btn_add_subt:
            command:
                - raw:Z6WHAC8CAACbBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAEAAAEAAAABAAEBAAEBAwIhAQEAAAAAAAEBAQAAAAAAAQABAAABAAAAAQABAQABAQAA==
        btn_stop:
            command:
                - raw:Z6WHAC8CAACcBgAAphEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAQEAAAABAAEAAAEBAQABAwIhAQEAAAAAAAEBAQAAAAAAAAEBAAAAAQABAAABAQEAAQAA==
        btn_rewind:
            command:
                - raw:Z6WHAC8CAACbBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAAEAAAABAAABAAEBAQABAwIhAQEAAAAAAAEBAQAAAAAAAQABAAAAAQAAAQABAQEAAQAA==
        btn_f_rewind:
            command:
                - raw:Z6UfAgQCAABfAgAAZgYAAHIRAADcEQAA0LYAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0ISEhAQEBAQEhISEBAQEBASEBIQEBASEBASEBISEhASFRNCEhIQEBAQEBISEhAQEBAQEhASEBAQEhAQEhASEhIQEhUTQhISEBAQEBASEhIQEBAQEBIQEhAQEBIQEBIQEhISEBIWE0ISEhAQEBAQEhISEBAQEBASEBIQEBASEBASEBISEhASFhNCEhIQEBAQEBISEhAQEBAQEhASEBAQEhAQEhASEhIQEhUTQhISEBAQEBASEhIQEBAQEBIQEhAQEBIQEBIQEhISEBIVE0ISEhAQEBAQEhISEBAQEBASEBIQEBASEBASEBISEhASFRNCEhIQEBAQEBISEhAQEBAQEhASEBAQEhAQEhASEhIQEhAQ==
        btn_play:
            command:
                - raw:Z6WHAC4CAACfBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAABAQEAAAABAAAAAAEBAQABAwIhAQEAAAAAAAEBAQAAAAAAAQEBAAAAAQAAAAABAQEAAQAA==
        btn_pause:
            command:
                - raw:Z6WHAC8CAACbBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAQABAAABAAEAAQABAQABAwIhAQEAAAAAAAEBAQAAAAAAAAEAAQAAAQABAAEAAQEAAQAA==
        btn_forward:
            command:
                - raw:Z6WHAC8CAACdBgAApxEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAAABAAABAAEBAQABAQABAwIhAQEAAAAAAAEBAQAAAAAAAAAAAQAAAQABAQEAAQEAAQAA==
        btn_f_forward:
            command:
                - raw:Z6UfAi4CAACfBgAAqBEAADS3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiEBAQAAAAAAAQEBAAAAAAAAAAABAAABAAEBAQABAQABAwIhAQEAAAAAAAEBAQAAAAAAAAAAAQAAAQABAQEAAQEAAQMCIQEBAAAAAAABAQEAAAAAAAAAAAEAAAEAAQEBAAEBAAEDAiEBAQAAAAAAAQEBAAAAAAAAAAABAAABAAEBAQABAQABAwIhAQEAAAAAAAEBAQAAAAAAAAAAAQAAAQABAQEAAQEAAQMCIQEBAAAAAAABAQEAAAAAAAAAAAEAAAEAAQEBAAEBAAEDAiEBAQAAAAAAAQEBAAAAAAAAAAABAAABAAEBAQABAQABAwIhAQEAAAAAAAEBAQAAAAAAAAAAAQAAAQABAQEAAQEAAQAA==
